### ISSUE TITLE
Find biggest and second biggest contours

### ISSUE THREAD

**Issue by mduaneh** [FirewallRobotics/NanoVision5607#13]
https://github.com/FirewallRobotics/NanoVision5607/blob/e5f5a67829c0fa9dc36f3a43f21241cfc834f41c/opencv/hubVision.py#L102

We already find the biggest contour.
If we remove it from the list, and find the 2nd biggest contour we should be able to find the bounding box for the 2nd biggest.
See:  https://www.geeksforgeeks.org/python-program-to-find-second-largest-number-in-a-list/ "Method 3: By removing the max element from the list "
Then find the min and max X of the 2.

**Comment by Wendydarby** [comment]
Closing issue because for 2022 build
